### ISSUE TITLE
Mumber :)

### ISSUE THREAD

**Issue by ADingoAteMyXRP** [XRPL-Labs/XUMM-App#17]
Typo in text "mumber" should be "number"

https://github.com/XRPL-Labs/XUMM-App/blob/ff28d97f6dcb0bf1f0c03c2fe3bd825609b53145/src/locale/en.json#L279

**Comment by WietseWind** [comment]
Thank you @ADingoAteMyXRP :D Appreciate it, we'll fix it in the next release.
