### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by ADingoAteMyXRP** [XRPL-Labs/XUMM-App#19]
Typos and grammatical errors below!

--

https://github.com/XRPL-Labs/XUMM-App/blob/d3339c0b98d54e33464e1b75766f8cd0b0816368/src/locale/en.json#L154

[ ]
Was: "Biometric authentication is not supported in this devices!"
Should be: "Biometric authentication is not supported on this device!"

--

https://github.com/XRPL-Labs/XUMM-App/blob/d3339c0b98d54e33464e1b75766f8cd0b0816368/src/locale/en.json#L175

[ ]
capitalize "Make"

--

https://github.com/XRPL-Labs/XUMM-App/blob/d3339c0b98d54e33464e1b75766f8cd0b0816368/src/locale/en.json#L179

[ ]
Was: "Please add a account to sign the transaction"
Should be: "Please add an account to sign the transaction"

--

https://github.com/XRPL-Labs/XUMM-App/blob/d3339c0b98d54e33464e1b75766f8cd0b0816368/src/locale/en.json#L180

[ ]
Was: "Please add a account to send payments"
Should be: "Please add an account to send payments"

--

https://github.com/XRPL-Labs/XUMM-App/blob/d3339c0b98d54e33464e1b75766f8cd0b0816368/src/locale/en.json#L309

[ ]
Was: "Node is already exist!" 
Should be: "Node already exists!"

--

https://github.com/XRPL-Labs/XUMM-App/blob/d3339c0b98d54e33464e1b75766f8cd0b0816368/src/locale/en.json#L335

[ ]
Was: "Create an extended lenght passphrase that is easy to remember, but impossible for others to guess."
Should be: "Create an extended length passphrase that is easy to remember, but impossible for others to guess." (spelling of "length")

--

https://github.com/XRPL-Labs/XUMM-App/blob/d3339c0b98d54e33464e1b75766f8cd0b0816368/src/locale/en.json#L388

[ ]
Was: "How many words has your mnemonic?"
Should be: "How many words does your mnemonic have?"

--

https://github.com/XRPL-Labs/XUMM-App/blob/d3339c0b98d54e33464e1b75766f8cd0b0816368/src/locale/en.json#L411

[ ]
Was: "You are downgrading your access level, this will cause losing private key for this account. are you sure ?"
Should be: "You are downgrading your access level. This will cause you to lose your private key for this account. Are you sure?"

--

https://github.com/XRPL-Labs/XUMM-App/blob/d3339c0b98d54e33464e1b75766f8cd0b0816368/src/locale/en.json#L412

[ ]
Was: "You are removing this currency from your account, this action cannot be undo, are you sure?"
Should be: "You are removing this currency from your account. This action cannot be undone. Are you sure?"

--

https://github.com/XRPL-Labs/XUMM-App/blob/d3339c0b98d54e33464e1b75766f8cd0b0816368/src/locale/en.json#L415

[ ]
Was: "Account label should be less than 16 character!"
Should be: "Account label should be less than 16 characters!"

--

https://github.com/XRPL-Labs/XUMM-App/blob/d3339c0b98d54e33464e1b75766f8cd0b0816368/src/locale/en.json#L419

[ ]
Was: "Selected account is not activated, for sign this transaction you need to select a activated account!"
Should be: "Selected account is not activated. To sign this transaction you need to select an activated account!"

--

https://github.com/XRPL-Labs/XUMM-App/blob/d3339c0b98d54e33464e1b75766f8cd0b0816368/src/locale/en.json#L420

[ ]
Was: "Account already exist!"
Should be: "Account already exists!"

--

https://github.com/XRPL-Labs/XUMM-App/blob/d3339c0b98d54e33464e1b75766f8cd0b0816368/src/locale/en.json#L422

[ ]
Was: "Regular key account for this account does not imported with sign access!"

(I don't understand what this is trying to say -- might be "cannot be imported" instead of "does not imported" however the phrase may also mean "was not imported")

--

https://github.com/XRPL-Labs/XUMM-App/blob/d3339c0b98d54e33464e1b75766f8cd0b0816368/src/locale/en.json#L439

[]
Was: "Source and Destination address cannot be same!"
Should be: "Source and Destination address cannot be the same!"

--

https://github.com/XRPL-Labs/XUMM-App/blob/d3339c0b98d54e33464e1b75766f8cd0b0816368/src/locale/en.json#L464

[ ]
Was: "Selected account do not support selected currency."
Should be: "Selected account does not support selected currency."

--

https://github.com/XRPL-Labs/XUMM-App/blob/d3339c0b98d54e33464e1b75766f8cd0b0816368/src/locale/en.json#L466

[ ]
Was: "The destination account hasn't been used before, and doesn't have any balance. To activate an account on the XRP ledger, a initial deposit of at least 20 XRP is required."
Should be: "The destination account hasn't been used before, and doesn't have a balance. To activate an account on the XRP ledger, an initial deposit of at least 20 XRP is required."

--

https://github.com/XRPL-Labs/XUMM-App/blob/d3339c0b98d54e33464e1b75766f8cd0b0816368/src/locale/en.json#L476

[ ]
Was: "Cannot remove currency, error happened!"
Should be: "Cannot remove currency. Error occurred!"

--

https://github.com/XRPL-Labs/XUMM-App/blob/d3339c0b98d54e33464e1b75766f8cd0b0816368/src/locale/en.json#L485

[ ]
Was: "There is not enought liquidity, cannot exchange right now!"
Should be: "There is not enough liquidity. Cannot exchange right now!"
(spelling of enough)

Thanks for buidling!
ADingoAteMyXRP

**Comment by WietseWind** [comment]
Updated all of them. Grateful person here behind his laptop ;) Thank you! @ADingoAteMyXRP
