### ISSUE TITLE
Search bar for XUMM App

### ISSUE THREAD

**Issue by myxzlpltk** [XRPL-Labs/XUMM-App#65]
I have a lot of trustline to another token. While token list not sorted in ascending, it is hard for me to search token name. So please add search bar to filter token list. Or you can sort token list

**Comment by WietseWind** [comment]
We're already working on this. https://twitter.com/XummWallet/status/1463594832870494216

**Comment by myxzlpltk** [comment]
Is it already updated on android? I don't see the search bar?

**Comment by WietseWind** [comment]
We *are working* on this. It is not ready yet, and has not been released yet. It will be in a XUMM update in a couple of weeks.

**Comment by myxzlpltk** [comment]
Okay then. Have a nice day

**Comment by WietseWind** [comment]
Thanks, you too!
