### ISSUE TITLE
Feature Request: Split Screen Support

### ISSUE THREAD

**Issue by myxzlpltk** [XRPL-Labs/XUMM-App#67]
I know this is too much to ask since this app was specifically designed for mobile phone. I can see it in my tablet that all interfaces are oversize due to flex container. But will you add split screen support?

![1641488252402.jpg](https://user-images.githubusercontent.com/59659668/148420882-31d0ca8f-4817-48e2-a806-7b8c6eb239bf.jpg)

**Comment by WietseWind** [comment]
Thanks for your suggestion. We have a long back log, and will consider this at an appropriate time. May I ask you to post this here? https://feedback.xumm.dev

This allows other users to view & vote, so we get a sense of the urgency when we decide on the contents of our future development sprints.
