### ISSUE TITLE
[Bug] Change destination selection after 'Next' was clicked

### ISSUE THREAD

**Issue by nixer89** [XRPL-Labs/XUMM-App#81]
**Describe the bug**
One can change the account selection after the 'Next' button was clicked in the "Select recipient" screen. (See linked video)

**To Reproduce**
1. start a payment transaction
2. reach the "Select Recipient" screen
3. Select an account
4. Click 'Next'
5. Select a different account

**Expected behavior**
Account selection  should not be possible after 'Next' was clicked

**Screenshots**
https://gsuyeua.dlvr.cloud/RPReplay_Final1677254355.MP4

* XUMM version: [2.4.0.11]

What device are you running XUMM on?

* Manufacturer: [FILL THIS OUT]
* Model: [FILL THIS OUT]
* OS version: [FILL THIS OUT]
* Platforms
  * [ x] iOS
  * [ ] Android

**Comment by N3TC4T** [comment]
Thanks, fixed https://github.com/XRPL-Labs/XUMM-App/pull/72/commits/ba673ecebdb3b3ccc7a2d715ab1a159ba0531d6f
