### ISSUE TITLE
[Improvement] Show token issuer address 

### ISSUE THREAD

**Issue by N3TC4T** [XRPL-Labs/XUMM-App#85]
From twitter

```Showing up XRPL address of token which have symbol and icon updated. Right now we can't see of token issuer. Also provide copy this address option.```

We should add a way for user to be able to see the token address and also be able to copy it.

**Comment by WietseWind** [comment]
https://github.com/XRPL-Labs/XUMM-Issue-Tracker/projects/7#card-75925956
