### ISSUE TITLE
[Bug] Keyboard is not dismissed when focused on webview

### ISSUE THREAD

**Issue by N3TC4T** [XRPL-Labs/XUMM-App#88]
When keyboard is appeared by webview text inpue and lock screen appears, keyboard is not dismissed and blocks entering the Passcode

Platform: iOS

<img src="https://user-images.githubusercontent.com/6250203/228346635-0dbe1969-3243-4871-861a-4f3ed882daf7.jpeg" width="200px"/>

**Comment by WietseWind** [comment]
Also: https://mm.xrpledger.foundation/xrpgeeks/pl/5do493g1w7bz9gwxnhrhr97qjw

**Comment by N3TC4T** [comment]
Fixed in https://github.com/XRPL-Labs/XUMM-App/pull/89/commits/1f4b20865061cf5cf1fbefb361982a03963bf827
