### ISSUE TITLE
FinishEscrow - Submission Failed! invalidTransaction, Field 'OfferSequence' is required but missing

### ISSUE THREAD

**Issue by JulianKingman** [XRPL-Labs/XUMM-App#90]
**Describe the bug**
Can't finish an escrow because OfferSequence is missing

**To Reproduce**
1. Create an Escrow to your account (e.g. with Escrow Create xApp)
2. Click on Events
3. Click on the Escrow
4. Click Finish Escrow, and sign

**Expected behavior**
Escrow is finished and returned to account

**Screenshots**
![IMG_6ECB7D94A0BF-1](https://github.com/XRPL-Labs/XUMM-App/assets/1566400/a6c9fe68-98da-4733-be92-127b834479f7)

### Environment

What build of XUMM are you running? Please provide the full version (you can find it in Settings > Advanced).

* XUMM version: 2.5.0.4

What device are you running XUMM on?

* Manufacturer: Apple
* Model: iPhone 12 Pro
* OS version: 16.5.1(c)
* Platforms
  * [X] iOS
  * [ ] Android

**Comment by WietseWind** [comment]
Thanks for reporting.

This is not a bug on the Xumm side: this is the XRP Ledger reporting that a mandatory transaction field, OfferSequence, is missing.

Xumm will provide any field to the XRPL as provided by the creator of the payload.

This means that the original transaction sent to Xumm to sign didn't contain this field, meaning the payload creator can control this.

Where did you create the payload?

**Comment by JulianKingman** [comment]
In the "Escrow creator" xapp

**Comment by WietseWind** [comment]
Composing Escrows and other transactions is far too difficult and tricky for end users to let them manually add fields. 

In this case the composed transaction by the Escrow Creator is invalid, as per XRPL error. This will have to be discussed with the creator, looping @nixer89.

If you want to play around with manual JSON transactions, another tool by @nixer89 works well: "Raw JSON transactions": https://xrpl.services/tools

Or https://xumm.dev/signing-tool

**Comment by WietseWind** [comment]
Aaaah I see, you are just picking a random escrow from your history and trying to finish it with the Finish button in Xumm?

Are you willing to share your r-address (account) and escrow this is about with me?

**Comment by JulianKingman** [comment]
Yes, I can still reproduce it

Here's the r-address: rhJ6HKU4rLXGEkKHXLRoL7B61XvLz9JCem
and escrow (ledger index?): D887344380DB997C59EB7C663063A79DEEF077ADCCD0006C6A8151DB03C89E3D

**Comment by WietseWind** [comment]
That escrow doesn't exist on XRPL mainnet, nor does the r-address have an Escrow on mainnet.

Are you on a different network?

**Comment by JulianKingman** [comment]
oh yes, sorry, it's on testate.xrpl-labs.com

**Comment by WietseWind** [comment]
Aaaaaaaah ooh that explains everything!

So here's what happens:

To finish an escrow, one looks at the Escrow Ledger object.
Then at the PreviousTxn for the transaction that created the Escrow
Then you look up this transaction, and check the Sequence for that transaction

You can then finish the escrow with that Sequence that we look up. 

However, XRPL Testnet isn't full history. So when looking up the transaction that created the Escrow in the first place, the TX can't be found, hence the Sequence can't be looked up.

You can try changing nodes from XRPL Labs testnet to Ripple's Testnet, and if they don't have the history either, you'll have to find your Sequence some way (or try some things, down by one each time) and finish with a manually composed JSON transaction using e.g. https://xumm.dev/signing-tool and JSON like https://xrpl.org/escrowfinish.html

This is something that wouldn't happen on Mainnet, as there are several Full History machines available on mainnet.

**Comment by JulianKingman** [comment]
Bingo! Thank you so much for explaining.
